name: html_color
description: pacote para utilizar o padrão html
version: 0.0.1
author: Matheus Perez
homepage: matheusperez.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
